<?php

declare(strict_types=1);

namespace Dalfred\Service;

/**
 * Storage and validation for files generated by the Dalfred agent.
 *
 * No HTTP, no Dolibarr globals — call sites pass userId / config explicitly
 * so the service can be unit-tested and reused.
 */
class GeneratedFilesService
{
    public const ALLOWED_FORMATS = ['txt', 'csv', 'md', 'json', 'html'];

    public const MIME_MAP = [
        'txt'  => 'text/plain; charset=utf-8',
        'csv'  => 'text/csv; charset=utf-8',
        'md'   => 'text/markdown; charset=utf-8',
        'json' => 'application/json; charset=utf-8',
        'html' => 'application/octet-stream', // forced-download
    ];

    public const MAX_FILENAME_LEN = 100;

    public function __construct(
        private string $dataRoot,        // e.g. DOL_DATA_ROOT
        private int $maxSizeBytes,
        private string $downloadUrl = '' // full URL to download.php, resolved by the caller via dol_buildpath('/dalfred/download.php', 1). Empty = legacy '/custom/dalfred/download.php' fallback (broken on hosts with case-sensitive Custom/ dir or sub-path installs without DOL_URL_ROOT prefix)
    ) {}

    public function userDir(int $userId): string
    {
        return $this->dataRoot . '/dalfred/generated/user_' . $userId;
    }

    /**
     * Validate, sanitize and write a file for the given user.
     *
     * @return array{filename:string,size:int,download_url:string}
     * @throws \RuntimeException with code = stable error code (see spec §5.1)
     */
    public function create(int $userId, string $filename, string $format, string $content): array
    {
        if ($userId <= 0) {
            throw new \RuntimeException('InvalidUser');
        }
        $format = strtolower($format);
        if (!in_array($format, self::ALLOWED_FORMATS, true)) {
            throw new \RuntimeException('InvalidFormat');
        }
        if (strlen($content) > $this->maxSizeBytes) {
            throw new \RuntimeException('FileTooLarge');
        }

        $safeName = $this->sanitizeFilename($filename, $format);
        if ($safeName === '') {
            throw new \RuntimeException('InvalidFilename');
        }

        $dir = $this->userDir($userId);
        if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new \RuntimeException('WriteFailed');
        }

        $finalName = $this->resolveCollision($dir, $safeName);
        $path      = $dir . '/' . $finalName;

        // Defence-in-depth: realpath of resolved path must stay inside $dir.
        // We resolve the parent because the file doesn't exist yet.
        $parentReal = realpath(dirname($path));
        $dirReal    = realpath($dir);
        if ($parentReal === false || $dirReal === false
            || ($parentReal !== $dirReal && !str_starts_with($parentReal, $dirReal . DIRECTORY_SEPARATOR))) {
            throw new \RuntimeException('InvalidFilename');
        }

        if (file_put_contents($path, $content, LOCK_EX) === false) {
            throw new \RuntimeException('WriteFailed');
        }

        // If caller injected a resolved URL (preferred — uses dol_buildpath), use it as-is.
        // Else fall back to the legacy hardcoded path (broken on Custom/-cased dirs).
        $downloadBase = $this->downloadUrl !== ''
            ? $this->downloadUrl
            : '/custom/dalfred/download.php';

        return [
            'filename'     => $finalName,
            'size'         => filesize($path) ?: 0,
            'download_url' => $downloadBase . '?f=' . rawurlencode($finalName),
        ];
    }

    /**
     * - Removes path separators and dangerous chars.
     * - Strips any extension the caller may have included.
     * - Re-applies the format-derived extension.
     * - Truncates to MAX_FILENAME_LEN (extension included).
     * Returns '' if nothing usable remains.
     */
    public function sanitizeFilename(string $filename, string $format): string
    {
        // Strip any directory components and dangerous chars.
        $base = basename($filename);
        // Remove all but [A-Za-z0-9_.-] (NFKC-friendly conservative whitelist).
        $base = preg_replace('/[^A-Za-z0-9._-]+/', '_', $base) ?? '';
        // Remove leading dots so we don't end up with hidden files like ".php".
        $base = ltrim($base, '.');
        // Strip any extension the caller put in.
        $base = preg_replace('/\.[A-Za-z0-9]{1,8}$/', '', $base) ?? '';
        // Collapse repeated underscores for readability.
        $base = preg_replace('/_+/', '_', $base) ?? '';
        $base = trim($base, '_');

        if ($base === '') {
            return '';
        }

        $ext   = '.' . $format;
        $maxLen = self::MAX_FILENAME_LEN - strlen($ext);
        if ($maxLen <= 0) {
            return '';
        }
        if (strlen($base) > $maxLen) {
            $base = substr($base, 0, $maxLen);
        }
        return $base . $ext;
    }

    /**
     * Append _2, _3, … before the extension until the filename is free.
     */
    public function resolveCollision(string $dir, string $filename): string
    {
        $path = $dir . '/' . $filename;
        if (!file_exists($path)) {
            return $filename;
        }
        $dot  = strrpos($filename, '.');
        $stem = $dot === false ? $filename : substr($filename, 0, $dot);
        $ext  = $dot === false ? ''         : substr($filename, $dot);

        for ($i = 2; $i < 10000; $i++) {
            $candidate = $stem . '_' . $i . $ext;
            if (!file_exists($dir . '/' . $candidate)) {
                return $candidate;
            }
        }
        throw new \RuntimeException('WriteFailed');
    }

    /**
     * @return list<array{filename:string,size:int,modified:string,format:string}>
     */
    public function listForUser(int $userId): array
    {
        $dir = $this->userDir($userId);
        if (!is_dir($dir)) {
            return [];
        }
        $out = [];
        foreach (scandir($dir) ?: [] as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            $path = $dir . '/' . $entry;
            if (!is_file($path)) {
                continue;
            }
            $ext = strtolower(pathinfo($entry, PATHINFO_EXTENSION));
            if (!isset(self::MIME_MAP[$ext])) {
                continue; // never list files outside the whitelist
            }
            $out[] = [
                'filename' => $entry,
                'size'     => filesize($path) ?: 0,
                'modified' => gmdate('c', filemtime($path) ?: 0),
                'format'   => $ext,
            ];
        }
        // Sort by modified desc.
        usort($out, fn($a, $b) => strcmp($b['modified'], $a['modified']));
        return $out;
    }

    /**
     * @throws \RuntimeException with 'NotFound' or 'InvalidFilename'
     */
    public function delete(int $userId, string $filename): void
    {
        // Re-sanitize (basename only, no extension change).
        $safe = basename($filename);
        if ($safe === '' || $safe !== $filename) {
            throw new \RuntimeException('InvalidFilename');
        }
        $dir  = $this->userDir($userId);
        $path = $dir . '/' . $safe;

        $real    = realpath($path);
        $dirReal = realpath($dir);
        if ($real === false || $dirReal === false || !str_starts_with($real, $dirReal . DIRECTORY_SEPARATOR)) {
            throw new \RuntimeException('NotFound');
        }
        if (!is_file($real)) {
            throw new \RuntimeException('NotFound');
        }
        if (!unlink($real)) {
            throw new \RuntimeException('WriteFailed');
        }
    }
}
