<?php
/**
 * Forced-attachment download of files generated by the Dalfred agent.
 *
 * Always serves with Content-Disposition: attachment.
 * Never renders HTML inline (HTML files get application/octet-stream).
 *
 * The owning user is ALWAYS the authenticated session user — never trust any
 * URL parameter for user identification (IDOR prevention).
 */

$res = 0;
if (!$res && file_exists('../../main.inc.php'))    $res = @include '../../main.inc.php';
if (!$res && file_exists('../../../main.inc.php')) $res = @include '../../../main.inc.php';
if (!$res) die('Main include failed');

require_once dol_buildpath('/dalfred/src/Service/GeneratedFilesService.php');

if (empty($user->id)) {
    http_response_code(403);
    exit;
}
if (getDolGlobalString('DALFRED_FILE_GEN_ENABLED') !== '1') {
    http_response_code(403);
    exit;
}

$rawF     = GETPOST('f', 'alphanohtml');
$filename = dol_sanitizeFileName($rawF);
if ($filename === '' || $filename !== $rawF) {
    // sanitisation mutated the input → reject
    http_response_code(400);
    exit;
}

$svc      = new \Dalfred\Service\GeneratedFilesService(DOL_DATA_ROOT, PHP_INT_MAX, dol_buildpath('/dalfred/download.php', 1));
$userDir  = $svc->userDir((int) $user->id);
$filepath = $userDir . '/' . $filename;

$real    = realpath($filepath);
$dirReal = realpath($userDir);
if ($real === false || $dirReal === false || !str_starts_with($real, $dirReal . DIRECTORY_SEPARATOR)) {
    http_response_code(404);
    exit;
}
if (!is_file($real)) {
    http_response_code(404);
    exit;
}

$ext  = strtolower(pathinfo($real, PATHINFO_EXTENSION));
$mime = \Dalfred\Service\GeneratedFilesService::MIME_MAP[$ext] ?? null;
if ($mime === null) {
    http_response_code(403);
    exit;
}

while (ob_get_level()) ob_end_clean();
header('Content-Type: ' . $mime);
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . filesize($real));
header('X-Content-Type-Options: nosniff');
header('Cache-Control: private, no-store');
readfile($real);
exit;
