<?php
/**
 * "My files" — list, download and delete files generated by the Dalfred agent.
 */

$res = 0;
if (!$res && file_exists('../main.inc.php'))       $res = @include '../main.inc.php';
if (!$res && file_exists('../../main.inc.php'))    $res = @include '../../main.inc.php';
if (!$res && file_exists('../../../main.inc.php')) $res = @include '../../../main.inc.php';
if (!$res) die('Main include failed');

require_once dol_buildpath('/dalfred/src/Service/GeneratedFilesService.php');

$langs->loadLangs(['dalfred@dalfred']);

if (empty($user->id) || !$user->hasRight('dalfred', 'use')) {
    accessforbidden();
}

$action = GETPOST('action', 'aZ09');

// Delete action
if ($action === 'delete' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $token = GETPOST('token', 'alpha');
    if (!$token || $token !== currentToken()) {
        accessforbidden('CSRF token invalid');
    }
    $target = GETPOST('filename', 'alphanohtml');
    if ($target === '') {
        setEventMessages($langs->trans('ErrorInvalidFilename'), null, 'errors');
    } else {
        $svc = new \Dalfred\Service\GeneratedFilesService(DOL_DATA_ROOT, PHP_INT_MAX, dol_buildpath('/dalfred/download.php', 1));
        try {
            $svc->delete((int) $user->id, $target);
            setEventMessages($langs->trans('FileDeleted'), null, 'mesgs');
        } catch (\Throwable $e) {
            setEventMessages($langs->trans('ErrorDeletingFile'), null, 'errors');
        }
    }
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}

llxHeader('', $langs->trans('MyGeneratedFiles'), '');

print load_fiche_titre($langs->trans('MyGeneratedFiles'), '', 'fa-folder-open');

if (getDolGlobalString('DALFRED_FILE_GEN_ENABLED') !== '1') {
    print '<div class="opacitymedium">' . $langs->trans('FileGenerationDisabledByAdmin') . '</div>';
    llxFooter();
    exit;
}

$svc = new \Dalfred\Service\GeneratedFilesService(DOL_DATA_ROOT, PHP_INT_MAX, dol_buildpath('/dalfred/download.php', 1));
$files = $svc->listForUser((int) $user->id);

if (count($files) === 0) {
    print '<div class="opacitymedium">' . $langs->trans('NoFilesGenerated') . '</div>';
    llxFooter();
    exit;
}

$iconMap = [
    'txt'  => '📄',
    'csv'  => '📊',
    'md'   => '📝',
    'json' => '🧾',
    'html' => '🌐',
];

print '<div class="div-table-responsive-no-min">';
print '<table class="noborder centpercent">';
print '<tr class="liste_titre">';
print '<td>' . $langs->trans('Name') . '</td>';
print '<td class="right">' . $langs->trans('FileSize') . '</td>';
print '<td class="center">' . $langs->trans('FileCreatedAt') . '</td>';
print '<td class="center">' . $langs->trans('Actions') . '</td>';
print '</tr>';

foreach ($files as $f) {
    $icon = $iconMap[$f['format']] ?? '📁';
    $size = dol_print_size($f['size'], 1, 1);
    $date = dol_print_date(strtotime($f['modified']), 'dayhour');
    $dl   = dol_buildpath('/dalfred/download.php', 1) . '?f=' . rawurlencode($f['filename']);

    print '<tr class="oddeven">';
    print '<td>' . $icon . ' ' . dol_escape_htmltag($f['filename']) . '</td>';
    print '<td class="right">' . $size . '</td>';
    print '<td class="center">' . $date . '</td>';
    print '<td class="center">';

    // Download
    print '<a class="butAction" href="' . $dl . '" title="' . dol_escape_htmltag($langs->trans('DownloadFile')) . '">⬇️</a> ';

    // Delete (POST with CSRF)
    print '<form method="POST" action="' . $_SERVER['PHP_SELF'] . '" style="display:inline;"';
    print ' onsubmit="return confirm(\'' . dol_escape_js(sprintf($langs->trans('ConfirmDeleteFile'), $f['filename'])) . '\');">';
    print '<input type="hidden" name="token" value="' . newToken() . '">';
    print '<input type="hidden" name="action" value="delete">';
    print '<input type="hidden" name="filename" value="' . dol_escape_htmltag($f['filename']) . '">';
    print '<button type="submit" class="butActionDelete" title="' . dol_escape_htmltag($langs->trans('DeleteFile')) . '">🗑️</button>';
    print '</form>';

    print '</td>';
    print '</tr>';
}

print '</table>';
print '</div>';

llxFooter();
